### ISSUE TITLE
Building support for Python 3

### ISSUE THREAD

**Issue by darothen** [NCAR/PyReshaper#26]
Hi all,

I've had some success using PyReshaper outside the NCAR/CESM eco-system (it's been working well so far to handle a large GEOS-Chem archive which had been converted into COARDS-compliant NetCDF, running on our group's cluster), and anticipate continuing to use it in upcoming projects. 

However, to use PyReshaper I have to create an auxiliary Python environment just to accommodate its exclusivity on Python <=2.6. As best as I can tell, [mpi4py supports Python 3](http://mpi4py.readthedocs.io/en/stable/install.html#requirements), but neither [pynio](https://github.com/NCAR/PyNio) nor [ASAPPyTools](https://github.com/NCAR/ASAPPyTools) do. Are there active efforts to incorporate Python 3 support in either of these projects? @david-ian-brown [discussed upcoming Python 3+ support for pynio in a commit about a year ago](https://github.com/NCAR/pynio/commit/da51a30be0a8b51d8f9345c6bd3933aba098f696).

Since I'm going to be actively using PyReshaper over the next month while I implement a new data management plan for this archive, I'd be interested in actively contributing to Python 3 support for the NCAR libraries with anyone else working on them.

**Comment by kmpaul** [comment]
I'm pretty sure that the PyReshaper and ASAPPyTools both require Python <3 and >=2.6.

But, regardless, this is a problem.  I've been wanting to update the codebase of all of our software to support both 2.6+ and 3.3+ for quite a while, now, but I just haven't had time.  I know that everyone here at NCAR has had Python 3+ support on our schedule for a while, though.

**Comment by kmpaul** [comment]
@darothen Incidentally, I have recently added an "iobackends" feature to the PyReshaper allowing the user to select with backend (netCDF4-python or PyNIO) they want to use for I/O.  So, if PyNIO doesn't have Python3 support, then the PyReshaper should still work once I've updated its code.

**Comment by darothen** [comment]
@kmpaul that's extremely useful... I can drop that into one of my analysis pipelines once it's uploaded for testing/debugging.

**Comment by david-ian-brown** [comment]
I can add that it will definitely be a priority in the new year to get
PyNIO working with Python 3. Since PyNIO is written using the Python C API,
the changes needed are more extensive than for pure Python code.


On Thu, Dec 29, 2016 at 3:02 PM, Daniel Rothenberg <notifications@github.com

**Comment by kmpaul** [comment]
Just want everyone to know that I am open to a PR on this.  I don't have time to do this myself.  Not for quite some time, at least.

**Comment by CAM-Gerlach** [comment]
@kmpaul I haven't really used the package myself, but given I have general experience with both use of netCDF and Py3 porting, there is a test suite and CI support, and it seems this package is still developed with active users, I would be willing to lend a hand and help port it assuming I get some spare time over winter break. Given Python 2 will no longer be officially supported in 2 months and most of the major project have or are in the process of dropping Python 2 support, it would be up to you whether your goal is a to create and maintain a Python 2/3 cross-compatible port, or whether it makes more sense to simply port it directly to modern Python 3 and clean out the old Py2-only cruft at the same time.

**Comment by CAM-Gerlach** [comment]
However, I just double checked, and unfortunately it seems this project as well as a dependency you maintain (ASAPtools) is released under a restrictive [license](https://github.com/NCAR/PyReshaper/blob/master/LICENSE.rst) that is neither standard, free nor open source, unlike most of NCAR's other projects. While that is your and NCAR's choice as the maintainer and owner, I am afraid I cannot in good conscience spend my volunteer time and effort contributing to a project that the wider scientific community is not free to use, share and build upon, cannot be legally used with other freely-licensed software (e.g. anything GPL), and cannot be distributed with most free OSes, including the majority of mainstream Linux distros.

**Comment by kmpaul** [comment]
@CAM-Gerlach CRAAAAAAAAAP!   You are completely correct.  Since the first writing of the PyReshaper, though, NCAR has changed our policies on software licensing.  Now, NCAR legal encourages the use of Apache 2.0.  **SO**, here's what I propose:  

- [ ]  I will create a new issue related to changing the license to Apache 2.0.
- [ ] In that issue, I will ask all of the code contributors if they support changing the license.
- [ ] If **all** code contributors approve the switch to the Apache 2.0 license, then I will change the license in the `master` branch of the PyReshaper.

And that should do it.  Then you can contribute code...and your contributions will be **most** welcome!

**Comment by CAM-Gerlach** [comment]
No worries, that's great news! I was hoping this might be the case since the license hadn't been touched in almost 5 years. Apache 2.0 was what I was going to suggest if I had to pick one since a lot of other NCAR stuff uses it and its a decent balance between permissive but with some additional protections useful for organizationally-sponsored projects like this.

Sounds like you're well aware of how to go about a reliscending. I don't know about the other contributor you mentioned since their code doesn't show up on this Github repo, but In case you happen to never hear back from `sherimickelson`, it looks like they only contributed 7 lines of code (plus a doc rebuild) which would likely be considered to be too trivial and obvious to be protected by copyright i.e., another dev blackboxing the same thing would write identical lines), with the possible exception of the code comments and docstring lines which could simply be rewritten. 

I assume you are going to do something similar for ASAPPPy as well, since its also under the same old license and is a nonfree dependency of PyReshaper? Looks like `andersy005` made a smattering of minor changes to the build and CI files, and like this repo ` `dchandan` has a fork but Github doesn't actually report any of their changes being present in the upstream.

**Comment by kmpaul** [comment]
I have just opened an issue to update the license of ASAPPyTools, too.

https://github.com/NCAR/ASAPPyTools/issues/20

And @andersy005 works down the hall from me.  So, I think we can get that updated, too.

**Comment by dchandan** [comment]
I approve changing the license.

**Comment by CAM-Gerlach** [comment]
Thanks @dchandan , please note that #49 is the issue to comment on to document that. Thanks!

**Comment by kmpaul** [comment]
It's fine to place the approval here.  The issues are cross-referenced.

**Comment by kmpaul** [comment]
@CAM-Gerlach As of PR #50, PyReshaper should be switched to the Apache 2.0 license.

**Comment by CAM-Gerlach** [comment]
Great, thanks so much @kmpaul ! Hopefully I'll get some time to work on it over my short winter vacation; in the mean time I've got [another side project](https://www.star-fleet.tours/) to run...

**Comment by CAM-Gerlach** [comment]
@kmpaul Now that I might have a window of time for this (although not as much as I would have liked), is dropping Python 2 support also desired? The latter seems to be what NCAR projects and the Python community in general are moving toward (or already there) but it depends on how much this module is depended on by other libraries; it would seem to a relatively naive observer that is mostly used as a script/application rather than a library that other applications depend on (meaning that a transition period may not be necessary).

Dropping Py2 support makes things simpler since this wouldn't need to add a dep on `future` as the preferred library for dual support these days and cleans house of Py2 code while allowing use of Py3-only features, but if there are significant usecases where retaining Py2 compatibility temporarily is desired, then I can do either. Up to you.

**Comment by kmpaul** [comment]
@CAM-Gerlach Moving entirely to Py3 would please me, personally. However, it sounds like there are some post processing code that uses the PyReshaper and looks like it won’t update to Py3 any time soon. So, I would ideally like to see an update to Py3 support, continuing to support Py2, but making it easy to pull out Py2 at a later date when we know nobody still needs Py2 functionality anymore.

**Comment by CAM-Gerlach** [comment]
Okay; if we implement the Py2 compat layer with `future`, which is the recommended modern standard for such (as well as doing the conversion itself), it _should_ be _relatively_ straightforward to remove, and there may or may not actually be that much compatibility code present. Right now pyupgrade only supports automatic removal for the legacy `six`, but hopefully by then it will add `future` support (or maybe I will).

**Comment by kmpaul** [comment]
I believe that #54 resolves this issue.  Sorry it's been a *LONG* wait for Python3 support, but I think it is working, now.

**Comment by kmpaul** [comment]
I was bit pre-mature closing the issue.  I don't want to tempt fate.  ...waiting for tests to pass.

**Comment by kmpaul** [comment]
Ok.  Tests pass and a new release is on PyPI.

**Comment by CAM-Gerlach** [comment]
Thanks @kmpaul ! Sorry, I got busier than expected with my research, Spyder development, and now Project Mjolnir, a new open-source IoT ecosystem for remote environmental sensor networks. Glad to see this is finally ported!

> I was bit pre-mature closing the issue. I don't want to tempt fate. ...waiting for tests to pass.

Just in case you're unaware, you can automatically link an issue to a PR and close it after tests past and its merged by writing ``Fix #NNNN`` somewhere of the PR OP. Neat little Github feature.

**Comment by kmpaul** [comment]
@CAM-Gerlach.  Yeah.  I am aware of the `Fix #NN` and `Closes #NN` feature.  I just forget.  😄

**Comment by CAM-Gerlach** [comment]
Haha, happens to all of us :smile:
